deploy:
  runs-on: ubuntu-latest
  needs: build
  environment:
    name: 'Production'
  permissions:
    id-token: write
    contents: read

  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app
    
    - name: Unzip artifact
      run: unzip node-app.zip
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        auth-type: SERVICE_PRINCIPAL
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
    
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'hithere-backend'
        slot-name: 'Production'
        package: .
        app_build_command: 'echo "No build required"'
